default_context:
  project_name: 'dnd-webapp'
  project_slug: 'dnd-webapp'
  domain_main: 'dnd-webapp.com'
  domain_staging: 'stag.dnd-webapp.com'
  docker_swarm_stack_name_main: 'dnd-webapp-com'
  docker_swarm_stack_name_staging: 'stag-dnd-webapp-com'
  secret_key: 'c106959717756c0220f50a3c102c3a24dd496fdf07e969491eb073b1461b6842'
  first_superuser: 'admin@dnd-webapp.com'
  first_superuser_password: '621beea7a4bbbd85fc5ca1c6687db7ccc892987625d80e536aa7943162cbdc0c'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.dnd-webapp.com", "https://stag.dnd-webapp.com", "https://dnd-webapp.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@dnd-webapp.com'
  postgres_password: '3bdd71bee7b01a5b88c47459626d0b5fe64d595d8d0da5f57f5661405048bab4'
  pgadmin_default_user: 'admin@dnd-webapp.com'
  pgadmin_default_user_password: '621beea7a4bbbd85fc5ca1c6687db7ccc892987625d80e536aa7943162cbdc0c'
  traefik_constraint_tag: 'dnd-webapp.com'
  traefik_constraint_tag_staging: 'stag.dnd-webapp.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:621beea7a4bbbd85fc5ca1c6687db7ccc892987625d80e536aa7943162cbdc0c'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
